### ISSUE TITLE
Problem running PlasGUN

### ISSUE THREAD

**Issue by eperezv** [zhenchengfang/PlasGUN#2]
Hello,

I am trying to run PlasGUN on my dataset and I run into some problems:
I followed the manual to properly install the program. Do you have any idea of how to solve it? Thanks
```
(plasgun) e@e-PC:$ PlasGUN contigs.fasta plasgun/GT
Using TensorFlow backend.
predict.py:16: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  length=h5py.File('./tmp/length.mat')
predict.py:17: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  orftype=h5py.File('./tmp/orftype.mat')
predict.py:18: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  TIS_onehot=h5py.File('./tmp/TIS_onehot.mat')
predict.py:19: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  codon_onehot=h5py.File('./tmp/codon_onehot.mat')
Traceback (most recent call last):
  File "predict.py", line 44, in <module>
    main()
  File "predict.py", line 37, in main
    model=load_model(argv[1])
  File "/home/eduardo/miniconda3/envs/plasgun/lib/python2.7/site-packages/keras/models.py", line 233, in load_model
    with h5py.File(filepath, mode='r') as f:
  File "/home/eduardo/miniconda3/envs/plasgun/lib/python2.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/home/eduardo/miniconda3/envs/plasgun/lib/python2.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
IOError: Unable to open file (unable to open file: name = 'model_b.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Error using dlmread (line 62)
The file './tmp/predict.csv' could not be opened because: No such file or directory

Error in GenePredict (line 341)


Error in PlasGUN (line 35)

MATLAB:dlmread:FileNotOpened
```

**Comment by zhenchengfang** [comment]
Sorry for the late reply. I guessed that this problem may caused by the version of h5py (it seemed that the version of h5py was 3.0 in your machine). I think that you can try the virtual machine of PlasGUN. We have released a virtual machine in which all dependent software has been installed. The virtual machine can be downloaded at http://cqb.pku.edu.cn/ZhuLab/PPR_Meta/VM_Bioinfo.vdi.7z. The package of PlasGUN is on the desktop of the virtual machine. Also, you can refer to the manual (http://cqb.pku.edu.cn/ZhuLab/PPR_Meta/Manual-v1.1.pdf) to see how to install the virtual machine (quite easy). Note that the manual is for PPR-Meta, a tool that we released earlier, but the approaches of installing the virtual machine for both PPR-Meta and PlasGUN are the same.
