### ISSUE TITLE
I didn't find Plasgun on the virtual machine

### ISSUE THREAD

**Issue by Remigio1** [zhenchengfang/PlasGUN#3]
Hello,
1 - I want to make annotation using Plasgun but I didn't find this program on the virtual machine. I installed the virtual machine using the guide: http://cqb.pku.edu.cn/ZhuLab/PPR_Meta/Manual-v1.1.pdf. Plasgun is not present on the virtual machine?

2 - I want to get a gff file by Plasgun is it possible?

3 - do you have any plans to incorporate the plasgun into the bioconda?

4 - on ubuntu 19.04 I installed the plugin with all dependencies and followed the guide http://cqb.pku.edu.cn/ZhuLab/PPR_Meta/Manual-v1.1.pdf. but I was not successful.
below I send a part of the error:

$ PlasGUN example.fna resulted.csv
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast
Using TensorFlow backend.
Traceback (most recent call last):
  File "predict.py", line 3, in <module>
    from keras.models import Sequential
  File "/home/l/.local/lib/python2.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/l/.local/lib/python2.7/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/home/l/.local/lib/python2.7/site-packages/keras/utils/conv_utils.py", line 3, in <module>
    from .. import backend as K
  File "/home/l/.local/lib/python2.7/site-packages/keras/backend/__init__.py", line 83, in <module>
    from .tensorflow_backend import *
  File "/home/l/.local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf
  File "/home/l/.local/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/l/.local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
from tensorflow.python import pywrap_tensorflow
  File "/home/l/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/l/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/l/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/l/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory
Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/install_sources#common_installation_problems
for some common reasons and solutions. include the entire stack trace
above this error message when asking for help.
Error using dlmread (line 62)
The file './tmp/predict.csv' could not be opened because: No such file or directory
Error in GenePredict (line 200)
Error in PlasGUN (line 35)
MATLAB:dlmread:FileNotOpened

5 - can you help me?

**Comment by zhenchengfang** [comment]
Hi,
You can copy the PlasGUN folder to the virtual machine and run the program directly. All the dependent software has been install in the virtual machine. Or you can download the PlasGUN package directly within the virtual machine using the wget command. I will try to make the software more easy to use in the future and thank you for your suggestion.

**Comment by zhenchengfang** [comment]
Hi,
You can copy the PlasGUN folder to the virtual machine and run the program directly. All the dependent software has been install in the virtual machine. Or you can download the PlasGUN package directly within the virtual machine using the wget command. I will try to make the software more easy to use in the future and thank you for your suggestion.

**Comment by Remigio1** [comment]
**thanks for the feedback,
I managed to use the plasgun on the virtual machine, I did as you suggested, but through the virtual machine there is not enough memory when the multifasta file is large. I send you the error that appeared this time:**

bioinfo@bioinfo:~/Desktop/PlasGUN_v_1_0$ ./PlasGUN fasta_recuperados/todos_recuperados_semrepeat_semrna_day01.fasta fasta_recuperados/plasgun_ORF_todos_recuperados_semrepeat_semrna_day01.csv
/usr/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
2021-10-10 08:05:10.507409: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2
Error using cat
Out of memory. Type HELP MEMORY for your options.
Error in cell2mat
Error in GenePredict (line 325)
Error in PlasGUN (line 35)
MATLAB:nomem

**Do you have any suggestion?**

**Comment by zhenchengfang** [comment]
Sorry for the late reply, I am busing with another work. I will write a script to optimize the memory usage in these tow days.

**Comment by Remigio1** [comment]
Thanks for the service, I'll be waiting for the script

**Comment by zhenchengfang** [comment]
Hi, you may try to copy the file PlasGUN_v_1_1 to the PlasGUN folder in the virtual machine. You can type the command:

PlasGUN_v_1_1 example.fna result -b 100 

The "-b" option is designed to split the file into several small files, and the number of sequence in each file is specified by "-b". If the virtual machine does not contain enough memory, you can specify a smaller "-b".

**Comment by zhenchengfang** [comment]
Hi, you may try to copy the file PlasGUN_v_1_1 to the PlasGUN folder in the virtual machine. You can type the command:

PlasGUN_v_1_1 example.fna result -b 100

The "-b" option is designed to split the file into several small files, and the number of sequence in each file is specified by "-b". If the virtual machine does not contain enough memory, you can specify a smaller "-b".

**Comment by Remigio1** [comment]
Hi, I still can't:

bioinfo@bioinfo:~/Desktop/PlasGUN_v_1_0$ ./PlasGUN fasta_recuperados/todos_recuperados_semrepeat_semrna_day01.fasta result -b 100
Error using PlasGUN
Too many input arguments.
MATLAB:TooManyInputs
Error:Too many input arguments.

**Comment by zhenchengfang** [comment]
Sorry for the late reply. I have checked the file and it could run. The updated command is:
./PlasGUN_v_1_1 example.fna result -b 100
rather than:
./PlasGUN example.fna result -b 100
You can copy the file PlasGUN_v_1_1 (https://github.com/zhenchengfang/PlasGUN/blob/master/PlasGUN_v_1_1) to the original PlasGUN folder and run the command.

**Comment by Remigio1** [comment]
I downloaded PlasGUN_v_1_1 and had to make the program executable with "$ chmod +x PlasGUN_v_1_1" and then it worked correctly. Thank you so much for helping me.
